// Battlefield unit sprites for the manual battle arena. Sits alongside
// paint2dDefaults.ts (NOT inside paint2d/) for the same reason: it touches the
// Vite-`?url`-coupled assetDescriptors.ts/assets.ts, so the painter itself and
// the node:test-importable arena modules must never import it directly. The
// arena's browser entry point injects the resolver this module builds.
//
// Sprites are generated by `npm run models:build` -- see docs/unit-models.md.

import { UNIT_DESCRIPTORS, unitKey } from "./assetDescriptors";
import type { SpriteDescriptor } from "./assetDescriptors";
import { ImageSpriteSource } from "./assetSource";
import { SpriteProvider } from "./assets";
import type {
  Paint2DSpriteResolver,
  ResolvedSprite,
  UnitFacing,
} from "./scene/paint2d/deps";

let provider: SpriteProvider | null = null;

function unitSpriteProvider(): SpriteProvider {
  if (provider) return provider;

  const descriptors: SpriteDescriptor[] = Object.values(UNIT_DESCRIPTORS);
  const urls: Record<string, string> = {};
  for (const d of descriptors) {
    if (d.url) urls[d.key] = d.url;
  }

  provider = new SpriteProvider(new ImageSpriteSource(urls), descriptors);
  provider.preload();
  return provider;
}

export function resolveUnitSprite(
  unitTypeId: string,
  facing: UnitFacing,
): ResolvedSprite | undefined {
  const resolved = unitSpriteProvider().resolve(unitKey(unitTypeId, facing));
  if (!resolved) return undefined;
  return {
    drawable: resolved.drawable,
    descriptor: resolved.descriptor,
    ready: resolved.ready,
  };
}

// A Paint2DSpriteResolver that only answers unit queries. The arena's scene
// contains nothing but battle-kind nodes, so the other four resolvers are
// never consulted -- see buildArenaPaint2dDeps() in
// src/screens/combat/arena/paint.ts.
export function createArenaSpriteResolver(): Paint2DSpriteResolver {
  return {
    resolveSpriteForResource: () => undefined,
    resolveSpriteForHero: () => undefined,
    resolveSpriteForBuilding: () => undefined,
    resolveSpriteForCastle: () => undefined,
    resolveSpriteForUnit: resolveUnitSprite,
    resolveSprite: () => undefined,
  };
}
