-- Idempotent: each ALTER uses IF NOT EXISTS where possible.
ALTER TABLE games
  ADD COLUMN IF NOT EXISTS round INT NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS active_player_id INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS players JSONB NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS heroes JSONB NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS settlements JSONB NOT NULL DEFAULT '{}'::jsonb;
